version: '3.1'

services:
  app:
    container_name: ct-api-node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      mongoURI: mongodb://admin:password@mongodb:27017/dbSistemaMed?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
      
volumes:
  mongo-data:
    driver: local